// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcafEeXkm4Uz5xFlchlYtLk5vlDTCzn6c',
    appId: '1:546700769790:android:3c5348ff54192e0e30a8af',
    messagingSenderId: '546700769790',
    projectId: 'chatrealnotfake',
    storageBucket: 'chatrealnotfake.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHExNOUbP2fBe60feIo4U_8VTme1Oh-So',
    appId: '1:546700769790:ios:09ed6f2e411866b430a8af',
    messagingSenderId: '546700769790',
    projectId: 'chatrealnotfake',
    storageBucket: 'chatrealnotfake.firebasestorage.app',
    iosBundleId: 'com.example.minorproject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ3bBfr9lrizcx1ycCOU_VY1US6jwznrw',
    appId: '1:546700769790:web:68564ad0a3e148f130a8af',
    messagingSenderId: '546700769790',
    projectId: 'chatrealnotfake',
    authDomain: 'chatrealnotfake.firebaseapp.com',
    storageBucket: 'chatrealnotfake.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHExNOUbP2fBe60feIo4U_8VTme1Oh-So',
    appId: '1:546700769790:ios:09ed6f2e411866b430a8af',
    messagingSenderId: '546700769790',
    projectId: 'chatrealnotfake',
    storageBucket: 'chatrealnotfake.firebasestorage.app',
    iosBundleId: 'com.example.minorproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ3bBfr9lrizcx1ycCOU_VY1US6jwznrw',
    appId: '1:546700769790:web:fbe2a14d00da11ee30a8af',
    messagingSenderId: '546700769790',
    projectId: 'chatrealnotfake',
    authDomain: 'chatrealnotfake.firebaseapp.com',
    storageBucket: 'chatrealnotfake.firebasestorage.app',
  );

}